export const MEAL_DATA = "Dane Posiłku"
export const MEAL_TIME = "Pora Posiłku"
export const MEAL_STEPS = "Kroki Przygotowania"
export const MEAL_INCLUDES = "Posiłek Zawiera"
export const MEAL_ADD_PRODUCTS = "Dodaj Produkt"
export const MEAL_INGREDIENTS = "Skladniki Posilku"